### ISSUE TITLE
10. PC 默认滚动条样式 scrollbar 设置

### ISSUE THREAD

**Issue by Jesonhu** [Jesonhu/keep#10]
```css
@media (-webkit-max-device-pixel-ratio: 1) {
    ::-webkit-scrollbar-track-piece {
        background-color:#FFF
    }

    ::-webkit-scrollbar {
        width: 6px;
        height: 6px
    }

    ::-webkit-scrollbar-thumb {
        background-color: #c2c2c2;
        background-clip: padding-box;
        min-height: 28px
    }

    ::-webkit-scrollbar-thumb:hover {
        background-color: #A0A0A0
    }
}
```

## [在线效果预览](https://developers.weixin.qq.com/miniprogram/dev/index.html)
![image](https://user-images.githubusercontent.com/18684575/47069209-ea826280-d220-11e8-9f8b-79d7dc5c6051.png)

### 相关资料
+ [源码-搜索 `scrollbar`](https://developers.weixin.qq.com/miniprogram/assets/style.css)
